Update rbac.yaml for fix invalid yaml
The RBAC is missing one line. When using kustomize:

Error: map[string]interface {}(nil): yaml: unmarshal errors:
  line 19: mapping key "resources" already defined at line 17
  line 20: mapping key "verbs" already defined at line 18